import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import LocatorInitializer from "@/locator";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="max-w-7xl mx-auto p-5">
          {process.env.NODE_ENV === "development" && <LocatorInitializer />}

          {children}
        </main>
      </body>
    </html>
  );
}